// <auto-generated />
using System;
using AeroTech.Ordering.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroTech.Ordering.Persistence.Migrations
{
    [DbContext(typeof(OrderingDbContext))]
    [Migration("20260921194857_S1HistoricalIdentityCorrection")]
    partial class S1HistoricalIdentityCorrection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Order")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AeroTech.Ordering.Domain.CommandReceiptAggregate.CommandReceipt", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("CallerScope")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CanonicalizationVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("CommandKind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("FinancialCustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("OwnerAirlineId")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAirlineId", "OrderId");

                    b.HasIndex("OwnerAirlineId", "CallerScope", "CommandKind", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CommandReceipts_Scope_Key");

                    b.ToTable("CommandReceipts", "Operations", t =>
                        {
                            t.HasCheckConstraint("CK_CommandReceipts_CommandKind_Enum", "[CommandKind] IN (2, 3)");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FareComponent", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AirFareId")
                        .HasColumnType("bigint");

                    b.Property<string>("BookingClass")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("CabinClassId")
                        .HasColumnType("int");

                    b.Property<string>("FareBasis")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FareFamily")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FareType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("PricingUnitId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RbdId")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int?>("TicketingRestrictionMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PricingUnitId", "Sequence")
                        .IsUnique();

                    b.ToTable("FareComponents", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_FareComponents_Sequence", "[Sequence] >= 1");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FareConstruction", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Assurance")
                        .HasColumnType("int");

                    b.Property<long>("CreatedByChangeId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderId", "CreatedByChangeId");

                    b.ToTable("FareConstructions", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_FareConstructions_Assurance_Enum", "[Assurance] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FareConstructionItem", b =>
                {
                    b.Property<long>("FareConstructionId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderItemId")
                        .HasColumnType("bigint");

                    b.HasKey("FareConstructionId", "OrderItemId");

                    b.HasIndex("OrderItemId");

                    b.ToTable("FareConstructionItems", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FarePricingUnit", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("FareConstructionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("SourceConstructionType")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FareConstructionId", "Sequence")
                        .IsUnique();

                    b.ToTable("FarePricingUnits", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_FarePricingUnits_Sequence", "[Sequence] >= 1");

                            t.HasCheckConstraint("CK_FarePricingUnits_SourceConstructionType_Enum", "[SourceConstructionType] IN (1, 2, 3, 4, 5, 6, 7, 8)");

                            t.HasCheckConstraint("CK_FarePricingUnits_Type_Enum", "[Type] IN (1, 2, 3, 4, 5, 6)");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FarePricingUnitCoveredBound", b =>
                {
                    b.Property<long>("PricingUnitId")
                        .HasColumnType("bigint");

                    b.Property<string>("CoveredBoundOfferId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("PricingUnitId", "CoveredBoundOfferId");

                    b.ToTable("FarePricingUnitCoveredBounds", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FundingObligation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ChangeId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderItemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderServiceId")
                        .HasColumnType("bigint");

                    b.Property<long>("PriceChangeSetId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PricingLineId")
                        .HasColumnType("bigint");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("OrderServiceId");

                    b.HasIndex("PricingLineId");

                    b.HasIndex("OrderId", "ChangeId");

                    b.HasIndex("OrderId", "PriceChangeSetId");

                    b.HasIndex("OrderId", "Id", "Version")
                        .IsUnique();

                    b.ToTable("FundingObligations", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_FundingObligations_Amount", "[AmountAmount] >= 0");

                            t.HasCheckConstraint("CK_FundingObligations_ExactlyOneScope", "(CASE WHEN [OrderItemId] IS NULL THEN 0 ELSE 1 END) + (CASE WHEN [OrderServiceId] IS NULL THEN 0 ELSE 1 END) + (CASE WHEN [PricingLineId] IS NULL THEN 0 ELSE 1 END) = 1");

                            t.HasCheckConstraint("CK_FundingObligations_Purpose_Enum", "[Purpose] IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_FundingObligations_Version", "[Version] >= 1");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("ActorContextType")
                        .HasColumnType("int");

                    b.Property<long?>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<int>("CommercialVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "CommercialVersion")
                        .IsUnique();

                    b.ToTable("OrderChanges", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_OrderChanges_ActorContextType_Enum", "[ActorContextType] IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("CK_OrderChanges_CommercialVersion", "[CommercialVersion] >= 1");

                            t.HasCheckConstraint("CK_OrderChanges_Type_Enum", "[Type] IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderComponentTotal", b =>
                {
                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("Component")
                        .HasColumnType("int");

                    b.Property<int>("Effect")
                        .HasColumnType("int");

                    b.Property<decimal>("CreditAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("DebitAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.HasKey("OrderId", "Component", "Effect");

                    b.ToTable("OrderComponentTotals", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_OrderComponentTotals_Component_Enum", "[Component] IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)");

                            t.HasCheckConstraint("CK_OrderComponentTotals_Effect_Enum", "[Effect] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_OrderComponentTotals_Magnitudes", "[DebitAmount] >= 0 AND [CreditAmount] >= 0");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderContact", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "Sequence")
                        .IsUnique();

                    b.ToTable("OrderContacts", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_OrderContacts_Role_Enum", "[Role] IN (1, 2, 3, 4, 5)");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("CommercialStatus")
                        .HasColumnType("int");

                    b.Property<long>("CreatedByChangeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "CommercialStatus");

                    b.HasIndex("OrderId", "CreatedByChangeId");

                    b.ToTable("OrderItems", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_OrderItems_AcceptedTotal", "[AcceptedTotalAmount] >= 0");

                            t.HasCheckConstraint("CK_OrderItems_CommercialStatus_Enum", "[CommercialStatus] IN (1, 2, 3, 4, 5, 6, 7)");

                            t.HasCheckConstraint("CK_OrderItems_Kind_Enum", "[Kind] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItemServiceLink", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("LinkedByChangeId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderIdAtAssociation")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderServiceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderServiceId");

                    b.HasIndex("OrderIdAtAssociation", "LinkedByChangeId");

                    b.HasIndex("OrderItemId", "OrderServiceId")
                        .IsUnique();

                    b.ToTable("OrderItemServiceLinks", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderJourney", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("BoundId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("int");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "BoundId")
                        .IsUnique();

                    b.HasIndex("OrderId", "Sequence")
                        .IsUnique();

                    b.ToTable("OrderJourneys", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_OrderJourneys_Direction_Enum", "[Direction] IN (1, 2)");

                            t.HasCheckConstraint("CK_OrderJourneys_Sequence", "[Sequence] >= 1");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegment", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int?>("AircraftId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationAirportTerminalId")
                        .HasColumnType("int");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<long?>("FlightCapacityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FlightId")
                        .HasColumnType("bigint");

                    b.Property<string>("FlightNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("FlightVersion")
                        .HasColumnType("int");

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int?>("MarketingAirlineId")
                        .HasColumnType("int");

                    b.Property<int?>("OperatingAirlineId")
                        .HasColumnType("int");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginAirportTerminalId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SoldArrival")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SoldDeparture")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId", "Sequence")
                        .IsUnique();

                    b.HasIndex("OrderId", "JourneyId");

                    b.ToTable("OrderSegments", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_OrderSegments_Kind_Enum", "[Kind] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_OrderSegments_Sequence", "[Sequence] >= 1");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegmentLeg", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ArrivalDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DepartureDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationAirportTerminalId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("LegId")
                        .HasColumnType("bigint");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginAirportTerminalId")
                        .HasColumnType("int");

                    b.Property<long>("SegmentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SegmentId", "LegId")
                        .IsUnique();

                    b.HasIndex("SegmentId", "Sequence")
                        .IsUnique();

                    b.ToTable("OrderSegmentLegs", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_OrderSegmentLegs_Sequence", "[Sequence] >= 1");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderService", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("CommercialStatus")
                        .HasColumnType("int");

                    b.Property<long>("CreatedByChangeId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrderId", "Id");

                    b.HasIndex("CreatedByChangeId");

                    b.HasIndex("OrderId", "OrderItemId");

                    b.HasIndex("OrderItemId", "CommercialStatus");

                    b.ToTable("OrderServices", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_OrderServices_CabinBaggageWeightUnit_Enum", "[CabinBaggageWeightUnit] IS NULL OR [CabinBaggageWeightUnit] IN (1, 2)");

                            t.HasCheckConstraint("CK_OrderServices_CheckedBaggageWeightUnit_Enum", "[CheckedBaggageWeightUnit] IS NULL OR [CheckedBaggageWeightUnit] IN (1, 2)");

                            t.HasCheckConstraint("CK_OrderServices_CommercialStatus_Enum", "[CommercialStatus] IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_OrderServices_DocumentAuthority_Enum", "[DocumentAuthority] IS NULL OR [DocumentAuthority] IN (1, 2)");

                            t.HasCheckConstraint("CK_OrderServices_FulfillmentDocumentKind_Enum", "[FulfillmentDocumentKind] IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_OrderServices_FulfillmentProfileAssurance_Enum", "[FulfillmentProfileAssurance] IN (1, 2)");

                            t.HasCheckConstraint("CK_OrderServices_FundingRequirement_Enum", "[FundingRequirement] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_OrderServices_ReservationRequirement_Enum", "[ReservationRequirement] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_OrderServices_ServiceType_Enum", "[ServiceType] IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22)");
                        });

                    b.HasDiscriminator<int>("ServiceType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderTraveller", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientTravellerRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("InfantParentTravellerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("PassengerTypeCode")
                        .HasColumnType("int");

                    b.Property<string>("SourceTravellerRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "ClientTravellerRef")
                        .IsUnique();

                    b.HasIndex("OrderId", "InfantParentTravellerId");

                    b.HasIndex("OrderId", "SourceTravellerRef")
                        .IsUnique();

                    b.ToTable("OrderTravellers", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_OrderTravellers_Guardian", "[InfantParentTravellerId] IS NULL OR [InfantParentTravellerId] <> [Id]");

                            t.HasCheckConstraint("CK_OrderTravellers_PassengerTypeCode_Enum", "[PassengerTypeCode] IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116)");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.PriceChangeSet", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ChangeId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FinancialSequence")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangeId")
                        .IsUnique();

                    b.HasIndex("OrderId", "ChangeId");

                    b.HasIndex("OrderId", "FinancialSequence")
                        .IsUnique();

                    b.ToTable("PriceChangeSets", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_PriceChangeSets_FinancialSequence", "[FinancialSequence] >= 1");

                            t.HasCheckConstraint("CK_PriceChangeSets_Reason_Enum", "[Reason] IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.PricingLine", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("BasisId")
                        .HasColumnType("bigint");

                    b.Property<int>("BasisType")
                        .HasColumnType("int");

                    b.Property<int>("CalculationKind")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Component")
                        .HasColumnType("int");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("Effect")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("PriceChangeSetId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reference")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SourceConversionRef")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceOccurrencePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrderId", "Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("OrderId", "OrderItemId");

                    b.HasIndex("OrderId", "PriceChangeSetId");

                    b.HasIndex("PriceChangeSetId", "SourceOccurrencePath")
                        .IsUnique();

                    b.ToTable("PricingLines", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_PricingLines_BasisType_Enum", "[BasisType] IN (1, 2, 3, 4, 5, 6, 7, 8)");

                            t.HasCheckConstraint("CK_PricingLines_CalculationKind_Enum", "[CalculationKind] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_PricingLines_CommissionNotCustomer", "NOT ([Component] = 9 AND [Effect] = 1)");

                            t.HasCheckConstraint("CK_PricingLines_Component_Enum", "[Component] IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)");

                            t.HasCheckConstraint("CK_PricingLines_Direction", "[Direction] IN (1, 2)");

                            t.HasCheckConstraint("CK_PricingLines_Direction_Enum", "[Direction] IN (1, 2)");

                            t.HasCheckConstraint("CK_PricingLines_Effect_Enum", "[Effect] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_PricingLines_OriginalMagnitude", "[OriginalValueAmount] >= 0");

                            t.HasCheckConstraint("CK_PricingLines_OtherInformational", "[Component] <> 11 OR [Effect] = 3");

                            t.HasCheckConstraint("CK_PricingLines_Role_Enum", "[Role] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_PricingLines_SaleMagnitude", "[SaleValueAmount] >= 0");

                            t.HasCheckConstraint("CK_PricingLines_SettlementAttribution", "([Effect] = 2 AND [SettlementPartyRef] IS NOT NULL AND [SettlementCategoryCode] IS NOT NULL) OR ([Effect] <> 2 AND [SettlementPartyRef] IS NULL AND [SettlementCategoryCode] IS NULL)");

                            t.HasCheckConstraint("CK_PricingLines_TaxNotSettlement", "NOT ([Component] = 3 AND [Effect] = 2)");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Order", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("AcceptedSnapshotDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("ClientReference")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("CommercialSummary")
                        .HasColumnType("int");

                    b.Property<int>("CommercialVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<long>("FinancialCustomerId")
                        .HasColumnType("bigint");

                    b.Property<int>("FinancialSequence")
                        .HasColumnType("int");

                    b.Property<int>("JourneyType")
                        .HasColumnType("int");

                    b.Property<long>("LastEventOrdinal")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastTicketingDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("OrderRevision")
                        .HasColumnType("bigint");

                    b.Property<long>("OwnerAirlineId")
                        .HasColumnType("bigint");

                    b.Property<long>("RootOrderId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SaleCurrencyCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SourceOfferId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<long>("SourcePreparationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAirlineId", "CommercialSummary");

                    b.HasIndex("OwnerAirlineId", "OrderReference")
                        .IsUnique()
                        .HasDatabaseName("UX_Orders_Owner_Reference");

                    b.HasIndex("OwnerAirlineId", "SourcePreparationId")
                        .IsUnique()
                        .HasDatabaseName("UX_Orders_Owner_SourcePreparation");

                    b.HasIndex("OwnerAirlineId", "FinancialCustomerId", "CreatedAt");

                    b.ToTable("Orders", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_Orders_BuyerContextType_Enum", "[BuyerContextType] IS NULL OR [BuyerContextType] IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("CK_Orders_Channel_Enum", "[Channel] IN (1, 2, 3, 4, 5, 99)");

                            t.HasCheckConstraint("CK_Orders_CommercialSummary_Enum", "[CommercialSummary] IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_Orders_InitiatingActorContextType_Enum", "[InitiatingActorContextType] IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("CK_Orders_JourneyType_Enum", "[JourneyType] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_Orders_Revisions", "[CommercialVersion] >= 1 AND [FinancialSequence] >= 0 AND [OrderRevision] >= 1 AND [LastEventOrdinal] >= 0");

                            t.HasCheckConstraint("CK_Orders_Root", "[RootOrderId] > 0");

                            t.HasCheckConstraint("CK_Orders_SellerContextType_Enum", "[SellerContextType] IS NULL OR [SellerContextType] IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("CK_Orders_SellingOfficeKind_Enum", "[SellingOfficeKind] IS NULL OR [SellingOfficeKind] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderPreparationAggregate.Entities.PreparationSourceEvidence", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EvidenceRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("PreparationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PreparationId", "EvidenceRef")
                        .IsUnique();

                    b.ToTable("PreparationSourceEvidence", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderPreparationAggregate.OrderPreparation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AcceptanceAssurance")
                        .HasColumnType("int");

                    b.Property<string>("AcceptanceProfile")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CallerScope")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CandidateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CanonicalizationVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ContractVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("FinancialCustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("OfferExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("OwnerAirlineId")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerBindingRef")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("PriceValidUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("PricedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProviderProfileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SnapshotDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("SourceOfferId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("SourceOwner")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourcePayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAirlineId", "FinancialCustomerId", "CapturedAt");

                    b.ToTable("OrderPreparations", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_OrderPreparations_AcceptanceAssurance_Enum", "[AcceptanceAssurance] IN (1, 2)");

                            t.HasCheckConstraint("CK_OrderPreparations_Digest", "LEN([SnapshotDigest]) = 64");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<long>("OwnerAirlineId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EventId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Consumer")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("ReceivedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OwnerAirlineId", "SourceSystem", "EventId", "Consumer")
                        .HasName("PK_InboxMessages");

                    b.HasIndex("ReceivedOn");

                    b.ToTable("InboxMessages", "dbo");
                });

            modelBuilder.Entity("AeroTech.Ordering.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("EventOrdinal")
                        .HasColumnType("bigint");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("LeaseExpiresOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("LeaseVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("StreamId")
                        .HasColumnType("bigint");

                    b.Property<string>("StreamKind")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("ProcessedOn", "LeaseExpiresOn");

                    b.HasIndex("StreamKind", "StreamId", "EventOrdinal")
                        .IsUnique()
                        .HasDatabaseName("UX_OutboxMessages_Stream_EventOrdinal")
                        .HasFilter("[StreamKind] IS NOT NULL");

                    b.ToTable("OutboxMessages", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_OutboxMessages_Stream", "([StreamKind] IS NULL AND [StreamId] IS NULL AND [EventOrdinal] IS NULL) OR ([StreamKind] IS NOT NULL AND [StreamId] IS NOT NULL AND [EventOrdinal] >= 1)");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderAirTransportService", b =>
                {
                    b.HasBaseType("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderService");

                    b.Property<string>("BookingClass")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("CabinClassId")
                        .HasColumnType("int");

                    b.Property<long?>("RbdId")
                        .HasColumnType("bigint");

                    b.Property<long>("SegmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("TravellerId")
                        .HasColumnType("bigint");

                    b.HasIndex("OrderId", "SegmentId");

                    b.HasIndex("OrderId", "TravellerId", "SegmentId")
                        .IsUnique()
                        .HasFilter("[TravellerId] IS NOT NULL AND [SegmentId] IS NOT NULL");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_OrderServices_CabinBaggageWeightUnit_Enum", "[CabinBaggageWeightUnit] IS NULL OR [CabinBaggageWeightUnit] IN (1, 2)");

                            t.HasCheckConstraint("CK_OrderServices_CheckedBaggageWeightUnit_Enum", "[CheckedBaggageWeightUnit] IS NULL OR [CheckedBaggageWeightUnit] IN (1, 2)");

                            t.HasCheckConstraint("CK_OrderServices_CommercialStatus_Enum", "[CommercialStatus] IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_OrderServices_DocumentAuthority_Enum", "[DocumentAuthority] IS NULL OR [DocumentAuthority] IN (1, 2)");

                            t.HasCheckConstraint("CK_OrderServices_FulfillmentDocumentKind_Enum", "[FulfillmentDocumentKind] IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_OrderServices_FulfillmentProfileAssurance_Enum", "[FulfillmentProfileAssurance] IN (1, 2)");

                            t.HasCheckConstraint("CK_OrderServices_FundingRequirement_Enum", "[FundingRequirement] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_OrderServices_ReservationRequirement_Enum", "[ReservationRequirement] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_OrderServices_ServiceType_Enum", "[ServiceType] IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22)");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.CommandReceiptAggregate.CommandReceipt", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany()
                        .HasForeignKey("OwnerAirlineId", "OrderId")
                        .HasPrincipalKey("OwnerAirlineId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FareComponent", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.FarePricingUnit", null)
                        .WithMany("Components")
                        .HasForeignKey("PricingUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FareConstruction", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("FareConstructions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", null)
                        .WithMany()
                        .HasForeignKey("OrderId", "CreatedByChangeId")
                        .HasPrincipalKey("OrderId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FareConstructionItem", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.FareConstruction", null)
                        .WithMany("Items")
                        .HasForeignKey("FareConstructionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItem", null)
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FarePricingUnit", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.FareConstruction", null)
                        .WithMany("PricingUnits")
                        .HasForeignKey("FareConstructionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FarePricingUnitCoveredBound", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.FarePricingUnit", null)
                        .WithMany("CoveredBounds")
                        .HasForeignKey("PricingUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FundingObligation", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("FundingObligations")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItem", null)
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderService", null)
                        .WithMany()
                        .HasForeignKey("OrderServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.PricingLine", null)
                        .WithMany()
                        .HasForeignKey("PricingLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", null)
                        .WithMany()
                        .HasForeignKey("OrderId", "ChangeId")
                        .HasPrincipalKey("OrderId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.PriceChangeSet", null)
                        .WithMany()
                        .HasForeignKey("OrderId", "PriceChangeSetId")
                        .HasPrincipalKey("OrderId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<long>("FundingObligationId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("AmountAmount");

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("int")
                                .HasColumnName("AmountCurrencyId");

                            b1.HasKey("FundingObligationId");

                            b1.ToTable("FundingObligations", "Order");

                            b1.WithOwner()
                                .HasForeignKey("FundingObligationId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Changes")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderComponentTotal", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("ComponentTotals")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderContact", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Contacts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItem", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", null)
                        .WithMany()
                        .HasForeignKey("OrderId", "CreatedByChangeId")
                        .HasPrincipalKey("OrderId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.Money", "AcceptedTotal", b1 =>
                        {
                            b1.Property<long>("OrderItemId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("AcceptedTotalAmount");

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("int")
                                .HasColumnName("AcceptedTotalCurrencyId");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("OrderItems", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("AcceptedTotal")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItemServiceLink", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("ItemServiceLinks")
                        .HasForeignKey("OrderIdAtAssociation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItem", null)
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderService", null)
                        .WithMany()
                        .HasForeignKey("OrderServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", null)
                        .WithMany()
                        .HasForeignKey("OrderIdAtAssociation", "LinkedByChangeId")
                        .HasPrincipalKey("OrderId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderJourney", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Journeys")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegment", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Segments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderJourney", null)
                        .WithMany()
                        .HasForeignKey("OrderId", "JourneyId")
                        .HasPrincipalKey("OrderId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegmentLeg", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegment", null)
                        .WithMany("Legs")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderService", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", null)
                        .WithMany()
                        .HasForeignKey("CreatedByChangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Services")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItem", null)
                        .WithMany()
                        .HasForeignKey("OrderId", "OrderItemId")
                        .HasPrincipalKey("OrderId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.FulfillmentProfileSnapshot", "FulfillmentProfile", b1 =>
                        {
                            b1.Property<long>("OrderServiceId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Assurance")
                                .HasColumnType("int")
                                .HasColumnName("FulfillmentProfileAssurance");

                            b1.Property<int?>("CapacityUnits")
                                .HasColumnType("int")
                                .HasColumnName("CapacityUnits");

                            b1.Property<string>("DeliveryControlPolicyRef")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("DeliveryControlPolicyRef");

                            b1.Property<string>("DependencyTreatmentPolicyRef")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("DependencyTreatmentPolicyRef");

                            b1.Property<int?>("DocumentAuthority")
                                .HasColumnType("int")
                                .HasColumnName("DocumentAuthority");

                            b1.Property<int>("DocumentKind")
                                .HasColumnType("int")
                                .HasColumnName("FulfillmentDocumentKind");

                            b1.Property<int>("FundingRequirement")
                                .HasColumnType("int")
                                .HasColumnName("FundingRequirement");

                            b1.Property<bool?>("PartialFulfillmentSupported")
                                .HasColumnType("bit")
                                .HasColumnName("PartialFulfillmentSupported");

                            b1.Property<string>("ProfileRef")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("FulfillmentProfileRef");

                            b1.Property<string>("ProfileVersion")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("FulfillmentProfileVersion");

                            b1.Property<int>("ReservationRequirement")
                                .HasColumnType("int")
                                .HasColumnName("ReservationRequirement");

                            b1.Property<string>("ResourceUnitPolicyRef")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("ResourceUnitPolicyRef");

                            b1.HasKey("OrderServiceId");

                            b1.ToTable("OrderServices", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderServiceId");
                        });

                    b.Navigation("FulfillmentProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderTraveller", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Travellers")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderTraveller", null)
                        .WithMany()
                        .HasForeignKey("OrderId", "InfantParentTravellerId")
                        .HasPrincipalKey("OrderId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.TravellerIdentity", "Identity", b1 =>
                        {
                            b1.Property<long>("TravellerId")
                                .HasColumnType("bigint");

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("date");

                            b1.Property<string>("GivenName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("Surname")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.HasKey("TravellerId");

                            b1.ToTable("OrderTravellerIdentities", "Order");

                            b1.WithOwner()
                                .HasForeignKey("TravellerId");
                        });

                    b.Navigation("Identity")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.PriceChangeSet", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("PriceChangeSets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", null)
                        .WithMany()
                        .HasForeignKey("OrderId", "ChangeId")
                        .HasPrincipalKey("OrderId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.PricingLine", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("PricingLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItem", null)
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.PriceChangeSet", null)
                        .WithMany()
                        .HasForeignKey("OrderId", "PriceChangeSetId")
                        .HasPrincipalKey("OrderId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.Money", "OriginalValue", b1 =>
                        {
                            b1.Property<long>("PricingLineId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("OriginalValueAmount");

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("int")
                                .HasColumnName("OriginalValueCurrencyId");

                            b1.HasKey("PricingLineId");

                            b1.ToTable("PricingLines", "Order");

                            b1.WithOwner()
                                .HasForeignKey("PricingLineId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.Money", "SaleValue", b1 =>
                        {
                            b1.Property<long>("PricingLineId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("SaleValueAmount");

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("int")
                                .HasColumnName("SaleValueCurrencyId");

                            b1.HasKey("PricingLineId");

                            b1.ToTable("PricingLines", "Order");

                            b1.WithOwner()
                                .HasForeignKey("PricingLineId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.AppliedConversion", "AppliedConversion", b1 =>
                        {
                            b1.Property<long>("PricingLineId")
                                .HasColumnType("bigint");

                            b1.Property<int>("DecimalPlaces")
                                .HasColumnType("int")
                                .HasColumnName("ConversionDecimalPlaces");

                            b1.Property<int>("FromCurrencyId")
                                .HasColumnType("int")
                                .HasColumnName("ConversionFromCurrencyId");

                            b1.Property<decimal>("Rate")
                                .HasPrecision(28, 12)
                                .HasColumnType("decimal(28,12)")
                                .HasColumnName("ConversionRate");

                            b1.Property<string>("RoundingToken")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("ConversionRoundingToken");

                            b1.Property<string>("SourceConversionRef")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("ConversionSourceRef");

                            b1.Property<int>("ToCurrencyId")
                                .HasColumnType("int")
                                .HasColumnName("ConversionToCurrencyId");

                            b1.HasKey("PricingLineId");

                            b1.ToTable("PricingLines", "Order");

                            b1.WithOwner()
                                .HasForeignKey("PricingLineId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.SettlementAttribution", "SettlementAttribution", b1 =>
                        {
                            b1.Property<long>("PricingLineId")
                                .HasColumnType("bigint");

                            b1.Property<string>("CategoryCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("SettlementCategoryCode");

                            b1.Property<string>("PartyRef")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("SettlementPartyRef");

                            b1.HasKey("PricingLineId");

                            b1.ToTable("PricingLines", "Order");

                            b1.WithOwner()
                                .HasForeignKey("PricingLineId");
                        });

                    b.Navigation("AppliedConversion");

                    b.Navigation("OriginalValue")
                        .IsRequired();

                    b.Navigation("SaleValue")
                        .IsRequired();

                    b.Navigation("SettlementAttribution");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Order", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderPreparationAggregate.OrderPreparation", null)
                        .WithMany()
                        .HasForeignKey("OwnerAirlineId", "SourcePreparationId")
                        .HasPrincipalKey("OwnerAirlineId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.Money", "CustomerTotal", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("CustomerTotalAmount");

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("int")
                                .HasColumnName("CustomerTotalCurrencyId");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.BuyerSnapshot", "Buyer", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint");

                            b1.Property<long?>("BuyerId")
                                .HasColumnType("bigint")
                                .HasColumnName("BuyerId");

                            b1.Property<int?>("ContextType")
                                .HasColumnType("int")
                                .HasColumnName("BuyerContextType");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.InitiatingActorSnapshot", "InitiatingActor", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint");

                            b1.Property<long?>("ActorId")
                                .HasColumnType("bigint")
                                .HasColumnName("InitiatingActorId");

                            b1.Property<int>("ContextType")
                                .HasColumnType("int")
                                .HasColumnName("InitiatingActorContextType");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.SalesContextSnapshot", "SalesContext", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Channel")
                                .HasColumnType("int")
                                .HasColumnName("Channel");

                            b1.Property<int?>("SellerContextType")
                                .HasColumnType("int")
                                .HasColumnName("SellerContextType");

                            b1.Property<long?>("SellerId")
                                .HasColumnType("bigint")
                                .HasColumnName("SellerId");

                            b1.Property<long?>("SellingOfficeId")
                                .HasColumnType("bigint")
                                .HasColumnName("SellingOfficeId");

                            b1.Property<int?>("SellingOfficeKind")
                                .HasColumnType("int")
                                .HasColumnName("SellingOfficeKind");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Buyer")
                        .IsRequired();

                    b.Navigation("CustomerTotal")
                        .IsRequired();

                    b.Navigation("InitiatingActor")
                        .IsRequired();

                    b.Navigation("SalesContext")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderPreparationAggregate.Entities.PreparationSourceEvidence", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderPreparationAggregate.OrderPreparation", null)
                        .WithMany("Evidence")
                        .HasForeignKey("PreparationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderAirTransportService", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegment", null)
                        .WithMany()
                        .HasForeignKey("OrderId", "SegmentId")
                        .HasPrincipalKey("OrderId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderTraveller", null)
                        .WithMany()
                        .HasForeignKey("OrderId", "TravellerId")
                        .HasPrincipalKey("OrderId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.BaggageAllowance", "CabinBaggage", b1 =>
                        {
                            b1.Property<long>("OrderAirTransportServiceId")
                                .HasColumnType("bigint");

                            b1.Property<int?>("Pieces")
                                .HasColumnType("int")
                                .HasColumnName("CabinBaggagePieces");

                            b1.Property<decimal?>("Weight")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("CabinBaggageWeight");

                            b1.Property<int?>("WeightUnit")
                                .HasColumnType("int")
                                .HasColumnName("CabinBaggageWeightUnit");

                            b1.HasKey("OrderAirTransportServiceId");

                            b1.ToTable("OrderServices", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderAirTransportServiceId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.BaggageAllowance", "CheckedBaggage", b1 =>
                        {
                            b1.Property<long>("OrderAirTransportServiceId")
                                .HasColumnType("bigint");

                            b1.Property<int?>("Pieces")
                                .HasColumnType("int")
                                .HasColumnName("CheckedBaggagePieces");

                            b1.Property<decimal?>("Weight")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("CheckedBaggageWeight");

                            b1.Property<int?>("WeightUnit")
                                .HasColumnType("int")
                                .HasColumnName("CheckedBaggageWeightUnit");

                            b1.HasKey("OrderAirTransportServiceId");

                            b1.ToTable("OrderServices", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderAirTransportServiceId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.SoldTermFlags", "SoldTerms", b1 =>
                        {
                            b1.Property<long>("OrderAirTransportServiceId")
                                .HasColumnType("bigint");

                            b1.Property<bool?>("Changeable")
                                .HasColumnType("bit")
                                .HasColumnName("SoldTermChangeable");

                            b1.Property<bool?>("Refundable")
                                .HasColumnType("bit")
                                .HasColumnName("SoldTermRefundable");

                            b1.Property<bool?>("Upgradable")
                                .HasColumnType("bit")
                                .HasColumnName("SoldTermUpgradable");

                            b1.HasKey("OrderAirTransportServiceId");

                            b1.ToTable("OrderServices", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderAirTransportServiceId");
                        });

                    b.Navigation("CabinBaggage");

                    b.Navigation("CheckedBaggage");

                    b.Navigation("SoldTerms")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FareConstruction", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("PricingUnits");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FarePricingUnit", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("CoveredBounds");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegment", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Order", b =>
                {
                    b.Navigation("Changes");

                    b.Navigation("ComponentTotals");

                    b.Navigation("Contacts");

                    b.Navigation("FareConstructions");

                    b.Navigation("FundingObligations");

                    b.Navigation("ItemServiceLinks");

                    b.Navigation("Items");

                    b.Navigation("Journeys");

                    b.Navigation("PriceChangeSets");

                    b.Navigation("PricingLines");

                    b.Navigation("Segments");

                    b.Navigation("Services");

                    b.Navigation("Travellers");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderPreparationAggregate.OrderPreparation", b =>
                {
                    b.Navigation("Evidence");
                });
#pragma warning restore 612, 618
        }
    }
}
