// <auto-generated />
using System;
using AeroTech.Ordering.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroTech.Ordering.Persistence.Migrations
{
    [DbContext(typeof(OrderingDbContext))]
    partial class OrderingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Order")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AeroTech.Ordering.Domain.CommandReceiptAggregate.CommandReceipt", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("CallerScope")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CanonicalizationVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("CommandKind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("FinancialCustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OperationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("OwnerAirlineId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PreparationId")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.HasIndex("OwnerAirlineId", "OrderId");

                    b.HasIndex("OwnerAirlineId", "CallerScope", "CommandKind", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CommandReceipts_Scope_Key");

                    b.ToTable("CommandReceipts", "Operations");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FareConstruction", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Assurance")
                        .HasColumnType("int");

                    b.Property<long>("CreatedByChangeId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderIdAtCreation")
                        .HasColumnType("bigint");

                    b.Property<string>("PricingUnitsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceContextRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("SupersededByConstructionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByChangeId");

                    b.HasIndex("OrderIdAtCreation")
                        .IsUnique()
                        .HasDatabaseName("UX_FareConstructions_CurrentPerOrder")
                        .HasFilter("[SupersededByConstructionId] IS NULL");

                    b.HasIndex("SupersededByConstructionId");

                    b.ToTable("FareConstructions", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FundingObligation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ChangeId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<string>("SourceDecisionRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("SupersededObligationId")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangeId");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("SupersededObligationId");

                    b.HasIndex("OrderId", "Id", "Version")
                        .IsUnique();

                    b.ToTable("FundingObligations", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_FundingObligations_Amount", "[AmountAmount] >= 0");

                            t.HasCheckConstraint("CK_FundingObligations_Version", "[Version] >= 1");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("ActorContextType")
                        .HasColumnType("int");

                    b.Property<long?>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<int>("CommercialVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceDecisionRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "CommercialVersion")
                        .IsUnique();

                    b.ToTable("OrderChanges", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderContact", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "Sequence")
                        .IsUnique();

                    b.ToTable("OrderContacts", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("CommercialStatus")
                        .HasColumnType("int");

                    b.Property<long>("CreatedByChangeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceItemRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceOfferItemRef")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByChangeId");

                    b.HasIndex("OrderId", "CommercialStatus");

                    b.HasIndex("OrderId", "SourceItemRef")
                        .IsUnique();

                    b.ToTable("OrderItems", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItemServiceLink", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("LinkedByChangeId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderIdAtAssociation")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderServiceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LinkedByChangeId");

                    b.HasIndex("OrderIdAtAssociation");

                    b.HasIndex("OrderServiceId");

                    b.HasIndex("OrderItemId", "OrderServiceId", "LinkedByChangeId")
                        .IsUnique();

                    b.ToTable("OrderItemServiceLinks", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegment", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("DestinationRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FlightRef")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SoldArrival")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SoldDeparture")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SourceSegmentRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "Sequence")
                        .IsUnique();

                    b.HasIndex("OrderId", "SourceSegmentRef")
                        .IsUnique();

                    b.ToTable("OrderSegments", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_OrderSegments_Sequence", "[Sequence] >= 1");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegmentLeg", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("SegmentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("SourceLegRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("SegmentId", "Sequence")
                        .IsUnique();

                    b.ToTable("OrderSegmentLegs", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderService", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("CommercialStatus")
                        .HasColumnType("int");

                    b.Property<long>("CreatedByChangeId")
                        .HasColumnType("bigint");

                    b.Property<string>("DetailSchema")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("DetailSchemaVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderItemId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("QuantityUnit")
                        .HasColumnType("int");

                    b.Property<int>("ServiceVersion")
                        .HasColumnType("int");

                    b.Property<string>("SourceServiceRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByChangeId");

                    b.HasIndex("OrderId", "SourceServiceRef")
                        .IsUnique();

                    b.HasIndex("OrderItemId", "CommercialStatus");

                    b.ToTable("OrderServices", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_OrderServices_Quantity", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_OrderServices_Version", "[ServiceVersion] >= 1");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderServiceBeneficiary", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<long>("TravelerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TravelerId");

                    b.HasIndex("ServiceId", "TravelerId")
                        .IsUnique();

                    b.ToTable("OrderServiceBeneficiaries", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderServiceCoverage", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("SegmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SegmentId");

                    b.HasIndex("ServiceId", "SegmentId")
                        .IsUnique();

                    b.ToTable("OrderServiceCoverage", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderTraveler", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientTravelerRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("InfantParentTravelerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("PassengerTypeCode")
                        .HasColumnType("int");

                    b.Property<string>("SourceTravellerRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("InfantParentTravelerId");

                    b.HasIndex("OrderId", "ClientTravelerRef")
                        .IsUnique();

                    b.HasIndex("OrderId", "SourceTravellerRef")
                        .IsUnique();

                    b.ToTable("OrderTravelers", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_OrderTravelers_Guardian", "[InfantParentTravelerId] IS NULL OR [InfantParentTravelerId] <> [Id]");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.PriceChangeSet", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("BaseCommercialVersion")
                        .HasColumnType("int");

                    b.Property<long>("ChangeId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FinancialSequence")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<string>("SourceDecisionRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ChangeId")
                        .IsUnique();

                    b.HasIndex("OrderId", "FinancialSequence")
                        .IsUnique();

                    b.ToTable("PriceChangeSets", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_PriceChangeSets_Sequence", "[FinancialSequence] >= 1");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.PricingLine", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("BasisId")
                        .HasColumnType("bigint");

                    b.Property<int>("BasisType")
                        .HasColumnType("int");

                    b.Property<string>("CandidateLineRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Component")
                        .HasColumnType("int");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("Effect")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderItemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OriginalPricingLineId")
                        .HasColumnType("bigint");

                    b.Property<long>("PriceChangeSetId")
                        .HasColumnType("bigint");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SourceBasisRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceConversionRef")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceLineRef")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("OriginalPricingLineId");

                    b.HasIndex("OrderId", "OrderItemId");

                    b.HasIndex("PriceChangeSetId", "CandidateLineRef")
                        .IsUnique();

                    b.ToTable("PricingLines", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_PricingLines_CommissionNotCustomer", "NOT ([Component] = 9 AND [Effect] = 1)");

                            t.HasCheckConstraint("CK_PricingLines_Direction", "[Direction] IN (1, 2)");

                            t.HasCheckConstraint("CK_PricingLines_OriginalMagnitude", "[OriginalValueAmount] >= 0");

                            t.HasCheckConstraint("CK_PricingLines_OtherInformational", "[Component] <> 11 OR [Effect] = 3");

                            t.HasCheckConstraint("CK_PricingLines_ReversalReference", "[Role] <> 2 OR [OriginalPricingLineId] IS NOT NULL");

                            t.HasCheckConstraint("CK_PricingLines_SaleMagnitude", "[SaleValueAmount] >= 0");

                            t.HasCheckConstraint("CK_PricingLines_TaxNotSettlement", "NOT ([Component] = 3 AND [Effect] = 2)");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Order", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("BuyerActorContextType")
                        .HasColumnType("int");

                    b.Property<long?>("BuyerActorId")
                        .HasColumnType("bigint");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<string>("ClientReference")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("CommercialSummary")
                        .HasColumnType("int");

                    b.Property<int>("CommercialVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("FinancialCustomerId")
                        .HasColumnType("bigint");

                    b.Property<int>("FinancialSequence")
                        .HasColumnType("int");

                    b.Property<long>("LastEventOrdinal")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("OrderRevision")
                        .HasColumnType("bigint");

                    b.Property<long>("OwnerAirlineId")
                        .HasColumnType("bigint");

                    b.Property<long>("RootOrderId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SaleCurrencyRef")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long?>("SellingOfficeId")
                        .HasColumnType("bigint");

                    b.Property<long>("SourcePreparationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SourcePreparationId");

                    b.HasIndex("OwnerAirlineId", "CommercialSummary");

                    b.HasIndex("OwnerAirlineId", "OrderReference")
                        .IsUnique()
                        .HasDatabaseName("UX_Orders_Owner_Reference");

                    b.HasIndex("OwnerAirlineId", "SourcePreparationId")
                        .IsUnique()
                        .HasDatabaseName("UX_Orders_Owner_SourcePreparation");

                    b.HasIndex("OwnerAirlineId", "FinancialCustomerId", "CreatedAt");

                    b.ToTable("Orders", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_Orders_Revisions", "[CommercialVersion] >= 1 AND [FinancialSequence] >= 0 AND [OrderRevision] >= 1 AND [LastEventOrdinal] >= 0");

                            t.HasCheckConstraint("CK_Orders_Root", "[RootOrderId] = [Id]");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderPreparationAggregate.Entities.PreparationSourceEvidence", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EvidenceRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("PreparationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PreparationId", "EvidenceRef")
                        .IsUnique();

                    b.ToTable("PreparationSourceEvidence", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderPreparationAggregate.OrderPreparation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AcceptanceAssurance")
                        .HasColumnType("int");

                    b.Property<string>("AcceptanceProfile")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ActorContextType")
                        .HasColumnType("int");

                    b.Property<long?>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<string>("CallerScope")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CandidateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CanonicalizationVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<string>("ClientReference")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("ConsumedByOrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContractVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("FinancialCustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OwnerAirlineId")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerBindingRef")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("PricedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProviderProfileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SellingOfficeId")
                        .HasColumnType("bigint");

                    b.Property<string>("SnapshotDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("SourceOfferId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("SourceOwner")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourcePayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumedByOrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderPreparations_ConsumedByOrderId")
                        .HasFilter("[ConsumedByOrderId] IS NOT NULL");

                    b.HasIndex("ConsumedAt", "CreatedAt");

                    b.HasIndex("OwnerAirlineId", "FinancialCustomerId", "CreatedAt");

                    b.ToTable("OrderPreparations", "Order", t =>
                        {
                            t.HasCheckConstraint("CK_OrderPreparations_Consumption", "([ConsumedByOrderId] IS NULL AND [ConsumedAt] IS NULL) OR ([ConsumedByOrderId] IS NOT NULL AND [ConsumedAt] IS NOT NULL)");

                            t.HasCheckConstraint("CK_OrderPreparations_Digest", "LEN([SnapshotDigest]) = 64");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<long>("OwnerAirlineId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EventId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Consumer")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("ReceivedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OwnerAirlineId", "SourceSystem", "EventId", "Consumer")
                        .HasName("PK_InboxMessages");

                    b.HasIndex("ReceivedOn");

                    b.ToTable("InboxMessages", "dbo");
                });

            modelBuilder.Entity("AeroTech.Ordering.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("EventOrdinal")
                        .HasColumnType("bigint");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("LeaseExpiresOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("LeaseVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("StreamId")
                        .HasColumnType("bigint");

                    b.Property<string>("StreamKind")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("ProcessedOn", "LeaseExpiresOn");

                    b.HasIndex("StreamKind", "StreamId", "EventOrdinal")
                        .IsUnique()
                        .HasDatabaseName("UX_OutboxMessages_Stream_EventOrdinal")
                        .HasFilter("[StreamKind] IS NOT NULL");

                    b.ToTable("OutboxMessages", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_OutboxMessages_Stream", "([StreamKind] IS NULL AND [StreamId] IS NULL AND [EventOrdinal] IS NULL) OR ([StreamKind] IS NOT NULL AND [StreamId] IS NOT NULL AND [EventOrdinal] >= 1)");
                        });
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FareConstruction", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", null)
                        .WithMany()
                        .HasForeignKey("CreatedByChangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("FareConstructions")
                        .HasForeignKey("OrderIdAtCreation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.FareConstruction", null)
                        .WithMany()
                        .HasForeignKey("SupersededByConstructionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.FundingObligation", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", null)
                        .WithMany()
                        .HasForeignKey("ChangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("FundingObligations")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItem", null)
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.FundingObligation", null)
                        .WithMany()
                        .HasForeignKey("SupersededObligationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<long>("FundingObligationId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("AmountAmount");

                            b1.Property<string>("CurrencyRef")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("AmountCurrencyRef");

                            b1.HasKey("FundingObligationId");

                            b1.ToTable("FundingObligations", "Order");

                            b1.WithOwner()
                                .HasForeignKey("FundingObligationId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Changes")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderContact", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Contacts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItem", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", null)
                        .WithMany()
                        .HasForeignKey("CreatedByChangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.Money", "AcceptedTotal", b1 =>
                        {
                            b1.Property<long>("OrderItemId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("AcceptedTotalAmount");

                            b1.Property<string>("CurrencyRef")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("AcceptedTotalCurrencyRef");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("OrderItems", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("AcceptedTotal")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItemServiceLink", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", null)
                        .WithMany()
                        .HasForeignKey("LinkedByChangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("ItemServiceLinks")
                        .HasForeignKey("OrderIdAtAssociation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItem", null)
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderService", null)
                        .WithMany()
                        .HasForeignKey("OrderServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegment", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Segments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegmentLeg", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegment", null)
                        .WithMany("Legs")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderService", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", null)
                        .WithMany()
                        .HasForeignKey("CreatedByChangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Services")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItem", null)
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.FulfillmentProfileSnapshot", "FulfillmentProfile", b1 =>
                        {
                            b1.Property<long>("OrderServiceId")
                                .HasColumnType("bigint");

                            b1.Property<int>("CapacityUnits")
                                .HasColumnType("int")
                                .HasColumnName("CapacityUnits");

                            b1.Property<int>("DocumentKind")
                                .HasColumnType("int")
                                .HasColumnName("DocumentKind");

                            b1.Property<string>("ProfileRef")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("FulfillmentProfileRef");

                            b1.Property<bool>("RequiresFunding")
                                .HasColumnType("bit")
                                .HasColumnName("RequiresFunding");

                            b1.Property<int>("ReservationRequirement")
                                .HasColumnType("int")
                                .HasColumnName("ReservationRequirement");

                            b1.HasKey("OrderServiceId");

                            b1.ToTable("OrderServices", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderServiceId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.AirTransportDetail", "AirTransport", b1 =>
                        {
                            b1.Property<long>("ServiceId")
                                .HasColumnType("bigint");

                            b1.Property<string>("BookingClass")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("CabinRef")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("FlightNumber")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("FlightVersion")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("MarketingCarrierRef")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("OperatingCarrierRef")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("RbdRef")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.HasKey("ServiceId");

                            b1.ToTable("AirTransportServiceDetails", "Order");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.Navigation("AirTransport");

                    b.Navigation("FulfillmentProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderServiceBeneficiary", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderService", null)
                        .WithMany("Beneficiaries")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderTraveler", null)
                        .WithMany()
                        .HasForeignKey("TravelerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderServiceCoverage", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegment", null)
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderService", null)
                        .WithMany("Coverage")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderTraveler", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderTraveler", null)
                        .WithMany()
                        .HasForeignKey("InfantParentTravelerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Travelers")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.TravelerIdentity", "Identity", b1 =>
                        {
                            b1.Property<long>("TravelerId")
                                .HasColumnType("bigint");

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("date");

                            b1.Property<string>("GivenName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("Surname")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.HasKey("TravelerId");

                            b1.ToTable("OrderTravelerIdentities", "Order");

                            b1.WithOwner()
                                .HasForeignKey("TravelerId");
                        });

                    b.Navigation("Identity")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.PriceChangeSet", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", null)
                        .WithMany()
                        .HasForeignKey("ChangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("PriceChangeSets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.PricingLine", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("PricingLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItem", null)
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.PricingLine", null)
                        .WithMany()
                        .HasForeignKey("OriginalPricingLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.PriceChangeSet", null)
                        .WithMany()
                        .HasForeignKey("PriceChangeSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.Money", "OriginalValue", b1 =>
                        {
                            b1.Property<long>("PricingLineId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("OriginalValueAmount");

                            b1.Property<string>("CurrencyRef")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("OriginalValueCurrencyRef");

                            b1.HasKey("PricingLineId");

                            b1.ToTable("PricingLines", "Order");

                            b1.WithOwner()
                                .HasForeignKey("PricingLineId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.Money", "SaleValue", b1 =>
                        {
                            b1.Property<long>("PricingLineId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("SaleValueAmount");

                            b1.Property<string>("CurrencyRef")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("SaleValueCurrencyRef");

                            b1.HasKey("PricingLineId");

                            b1.ToTable("PricingLines", "Order");

                            b1.WithOwner()
                                .HasForeignKey("PricingLineId");
                        });

                    b.Navigation("OriginalValue")
                        .IsRequired();

                    b.Navigation("SaleValue")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Order", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderPreparationAggregate.OrderPreparation", null)
                        .WithMany()
                        .HasForeignKey("SourcePreparationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.Money", "CustomerTotal", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("CustomerTotalAmount");

                            b1.Property<string>("CurrencyRef")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("CustomerTotalCurrencyRef");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.ValidityFact", "OfferValidity", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Owner")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("OfferValidityOwner");

                            b1.Property<string>("Reason")
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("OfferValidityReason");

                            b1.Property<string>("SourceRef")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("OfferValiditySourceRef");

                            b1.Property<int>("State")
                                .HasColumnType("int")
                                .HasColumnName("OfferValidityState");

                            b1.Property<DateTimeOffset?>("Value")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("OfferValidityValue");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.ValidityFact", "PriceValidity", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Owner")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("PriceValidityOwner");

                            b1.Property<string>("Reason")
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("PriceValidityReason");

                            b1.Property<string>("SourceRef")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("PriceValiditySourceRef");

                            b1.Property<int>("State")
                                .HasColumnType("int")
                                .HasColumnName("PriceValidityState");

                            b1.Property<DateTimeOffset?>("Value")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("PriceValidityValue");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.ValidityFact", "TicketingValidity", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Owner")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("TicketingValidityOwner");

                            b1.Property<string>("Reason")
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("TicketingValidityReason");

                            b1.Property<string>("SourceRef")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("TicketingValiditySourceRef");

                            b1.Property<int>("State")
                                .HasColumnType("int")
                                .HasColumnName("TicketingValidityState");

                            b1.Property<DateTimeOffset?>("Value")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("TicketingValidityValue");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.AcceptedSource", "AcceptedSource", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint");

                            b1.Property<int>("AcceptanceAssurance")
                                .HasColumnType("int")
                                .HasColumnName("AcceptanceAssurance");

                            b1.Property<string>("AcceptanceProfile")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("AcceptanceProfile");

                            b1.Property<DateTimeOffset>("AcceptedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("AcceptedAt");

                            b1.Property<DateTimeOffset>("CapturedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("SourceCapturedAt");

                            b1.Property<DateTimeOffset>("ClientAcceptedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ClientAcceptedAt");

                            b1.Property<string>("ContractVersion")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("AcceptedContractVersion");

                            b1.Property<string>("OwnerBindingRef")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("AcceptedOwnerBindingRef");

                            b1.Property<long>("PreparationId")
                                .HasColumnType("bigint")
                                .HasColumnName("AcceptedPreparationId");

                            b1.Property<DateTimeOffset>("PricedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("SourcePricedAt");

                            b1.Property<string>("ProviderProfileId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("AcceptedProviderProfileId");

                            b1.Property<string>("SnapshotDigest")
                                .IsRequired()
                                .HasMaxLength(64)
                                .IsUnicode(false)
                                .HasColumnType("char(64)")
                                .HasColumnName("AcceptedSnapshotDigest")
                                .IsFixedLength();

                            b1.Property<string>("SourceOfferId")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("nvarchar(2048)")
                                .HasColumnName("AcceptedSourceOfferId");

                            b1.Property<string>("SourceOwner")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("AcceptedSourceOwner");

                            b1.Property<string>("SourcePayloadHash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("AcceptedSourcePayloadHash");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("AcceptedSource")
                        .IsRequired();

                    b.Navigation("CustomerTotal")
                        .IsRequired();

                    b.Navigation("OfferValidity")
                        .IsRequired();

                    b.Navigation("PriceValidity")
                        .IsRequired();

                    b.Navigation("TicketingValidity")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderPreparationAggregate.Entities.PreparationSourceEvidence", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderPreparationAggregate.OrderPreparation", null)
                        .WithMany("Evidence")
                        .HasForeignKey("PreparationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderPreparationAggregate.OrderPreparation", b =>
                {
                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.ValidityFact", "OfferValidity", b1 =>
                        {
                            b1.Property<long>("OrderPreparationId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Owner")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("OfferValidityOwner");

                            b1.Property<string>("Reason")
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("OfferValidityReason");

                            b1.Property<string>("SourceRef")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("OfferValiditySourceRef");

                            b1.Property<int>("State")
                                .HasColumnType("int")
                                .HasColumnName("OfferValidityState");

                            b1.Property<DateTimeOffset?>("Value")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("OfferValidityValue");

                            b1.HasKey("OrderPreparationId");

                            b1.ToTable("OrderPreparations", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderPreparationId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.ValidityFact", "PriceValidity", b1 =>
                        {
                            b1.Property<long>("OrderPreparationId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Owner")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("PriceValidityOwner");

                            b1.Property<string>("Reason")
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("PriceValidityReason");

                            b1.Property<string>("SourceRef")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("PriceValiditySourceRef");

                            b1.Property<int>("State")
                                .HasColumnType("int")
                                .HasColumnName("PriceValidityState");

                            b1.Property<DateTimeOffset?>("Value")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("PriceValidityValue");

                            b1.HasKey("OrderPreparationId");

                            b1.ToTable("OrderPreparations", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderPreparationId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.ValidityFact", "TicketingValidity", b1 =>
                        {
                            b1.Property<long>("OrderPreparationId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Owner")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("TicketingValidityOwner");

                            b1.Property<string>("Reason")
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("TicketingValidityReason");

                            b1.Property<string>("SourceRef")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("TicketingValiditySourceRef");

                            b1.Property<int>("State")
                                .HasColumnType("int")
                                .HasColumnName("TicketingValidityState");

                            b1.Property<DateTimeOffset?>("Value")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("TicketingValidityValue");

                            b1.HasKey("OrderPreparationId");

                            b1.ToTable("OrderPreparations", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderPreparationId");
                        });

                    b.Navigation("OfferValidity")
                        .IsRequired();

                    b.Navigation("PriceValidity")
                        .IsRequired();

                    b.Navigation("TicketingValidity")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegment", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderService", b =>
                {
                    b.Navigation("Beneficiaries");

                    b.Navigation("Coverage");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Order", b =>
                {
                    b.Navigation("Changes");

                    b.Navigation("Contacts");

                    b.Navigation("FareConstructions");

                    b.Navigation("FundingObligations");

                    b.Navigation("ItemServiceLinks");

                    b.Navigation("Items");

                    b.Navigation("PriceChangeSets");

                    b.Navigation("PricingLines");

                    b.Navigation("Segments");

                    b.Navigation("Services");

                    b.Navigation("Travelers");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderPreparationAggregate.OrderPreparation", b =>
                {
                    b.Navigation("Evidence");
                });
#pragma warning restore 612, 618
        }
    }
}
